version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./BACKEND/uploads:/app/uploads
    restart: unless-stopped 